services:
  main-php:
    build:
      context: .
      dockerfile: docker/php.DockerFile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
  mysql:
    image: mysql:8.3.0
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=astel
      - MYSQL_USER=astel
      - MYSQL_PASSWORD=astel
    ports:
      - 3306:3306
